version: '3.1'

services:
  reverse-proxy:
    image: nginx:1.27.1-alpine
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web1
      - web2
    networks:
      - nginx_reverse_proxy_network


  web1:
    image: nginx:1.27.1-alpine
    container_name: web1
    volumes:
      - ./web1/:/usr/share/nginx/html
      - ./nginx/web1.conf:/etc/nginx/conf.d/default.conf:ro
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - nginx_reverse_proxy_network

  web2:
    image: nginx:1.27.1-alpine
    container_name: web2
    volumes:
      - ./web2/:/usr/share/nginx/html/web2/
      - ./nginx/web2.conf:/etc/nginx/conf.d/default.conf:ro
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - nginx_reverse_proxy_network
  wordpress:
    image: wordpress:php8.3-fpm-alpine
    restart: always
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
    expose:
      - "9000"  # Expose PHP-FPM port for Nginx
    networks:
      - wordpress_network
      - nginx_reverse_proxy_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wordpress_network
volumes:
  wordpress:
  db:
networks:
  nginx_reverse_proxy_network:
  wordpress_network: